import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MotoCard } from '../moto-card/moto-card';
import { Especificaciones } from '../especificaciones/especificaciones';

@Component({
  selector: 'app-comparador',
  standalone: true,
  imports: [CommonModule, MotoCard, Especificaciones],
  templateUrl: './comparador.html',
  styleUrls: ['./comparador.css'],
})
export class Comparador {

  motos = [

  {
    id: 1,
    nombre: "TVS Raider 125",
    img: "assets/raider125categorias3naked125.png",
    cilindraje: "124.8 cc, monocilíndrico, 4 tiempos, SOHC",
    potencia: "12.5 HP @ 7.500 rpm",
    torque: "11.2 Nm @ 6.000 rpm",
    refrigeracion: "Aire",
    alimentacion: "Inyección electrónica FI",
    transmision: "5 velocidades",
    frenos: "ABS de un canal + disco delantero y tambor trasero",
    suspDel: "Horquilla telescópica",
    suspTras: "Mono-shock",
    peso: "121 kg",
    tanque: "10 litros",
    altura: "795 mm",
    velMax: "95–100 km/h aprox."
  },
  {
    id: 2,
    nombre: "Hero Hunk 125R",
    img: "assets/herohunk125categorias3naked125.png",
    cilindraje: "124.6 cc, monocilíndrico, 4 tiempos, SOHC",
    potencia: "11.9 HP @ 7.500 rpm",
    torque: "11 Nm @ 6.000 rpm",
    refrigeracion: "Aire",
    alimentacion: "Inyección electrónica FI",
    transmision: "5 velocidades",
    frenos: "ABS de un canal + disco delantero y tambor trasero",
    suspDel: "Horquilla telescópica",
    suspTras: "Mono-shock",
    peso: "121 kg",
    tanque: "10 litros",
    altura: "795 mm",
    velMax: "95–100 km/h aprox."
  },
  {
    id: 3,
    nombre: "Pulsar NS 125",
    img: "assets/pulsarns125categorias3naked125.png",
    cilindraje: "124.6 cc, monocilíndrico, 4 tiempos, SOHC",
    potencia: "11.8 HP @ 8.500 rpm",
    torque: "11 Nm @ 6.500 rpm",
    refrigeracion: "Aire",
    alimentacion: "Inyección electrónica FI",
    transmision: "5 velocidades",
    frenos: "ABS de un canal + disco delantero y trasero",
    suspDel: "Horquilla telescópica",
    suspTras: "Mono-shock Nitrox",
    peso: "135 kg",
    tanque: "12 litros",
    altura: "800 mm",
    velMax: "110–115 km/h aprox."
  },
  {
    id: 4,
    nombre: "Akt CR4 125",
    img: "assets/aktcr4125categorias3naked125.png",
    cilindraje: "124.5 cc, monocilíndrico, 4 tiempos, SOHC",
    potencia: "11.7 HP @ 8.000 rpm",
    torque: "10.8 Nm @ 6.500 rpm",
    refrigeracion: "Aire",
    alimentacion: "Inyección electrónica FI",
    transmision: "5 velocidades",
    frenos: "Disco delantero + tambor trasero",
    suspDel: "Horquilla telescópica",
    suspTras: "Mono-shock",
    peso: "125 kg",
    tanque: "10 litros",
    altura: "780 mm",
    velMax: "100–105 km/h aprox."
  },
  {
    id: 5,
    nombre: "Akt NKD 125",
    img: "assets/aktnkd125categorias3naked125.png",
    cilindraje: "124 cc, monocilíndrico, 4 tiempos, SOHC",
    potencia: "11.6 HP @ 8.000 rpm",
    torque: "10.5 Nm @ 6.000 rpm",
    refrigeracion: "Aire",
    alimentacion: "Inyección electrónica FI",
    transmision: "5 velocidades",
    frenos: "Disco delantero + tambor trasero",
    suspDel: "Horquilla telescópica",
    suspTras: "Mono-shock",
    peso: "123 kg",
    tanque: "10 litros",
    altura: "780 mm",
    velMax: "100–105 km/h aprox."
  },
  {
    id: 6,
    nombre: "Pulsar N 125",
    img: "assets/pulsarn125categorias3naked125.png",
    cilindraje: "124.6 cc, monocilíndrico, 4 tiempos, SOHC",
    potencia: "11.8 HP @ 8.000 rpm",
    torque: "11 Nm @ 6.500 rpm",
    refrigeracion: "Aire",
    alimentacion: "Inyección electrónica FI",
    transmision: "5 velocidades",
    frenos: "ABS de un canal + disco delantero y trasero",
    suspDel: "Horquilla telescópica",
    suspTras: "Mono-shock Nitrox",
    peso: "135 kg",
    tanque: "12 litros",
    altura: "800 mm",
    velMax: "110–115 km/h aprox."
  },
  {
    id: 7,
    nombre: "KTM Duke 250",
    img: "assets/ktmduke250categorias3naked250.png",
    cilindraje: "248.8 cc, monocilíndrico, 4 tiempos, DOHC",
    potencia: "29 HP @ 9.000 rpm",
    torque: "24 Nm @ 7.250 rpm",
    refrigeracion: "Refrigeración líquida",
    alimentacion: "Inyección electrónica",
    transmision: "6 velocidades",
    frenos: "ABS de doble canal + discos delantero y trasero",
    suspDel: "Horquilla invertida WP APEX 43 mm",
    suspTras: "Mono-shock WP APEX",
    peso: "169 kg aprox.",
    tanque: "13.4 litros",
    altura: "822 mm",
    velMax: "140–150 km/h aprox."
  },
  {
    id: 8,
    nombre: "Pulsar N 250",
    img: "assets/pulsarn250categorias3naked250.png",
    cilindraje: "249.07 cc, monocilíndrico, 4 tiempos, SOHC",
    potencia: "24.1 HP @ 8.750 rpm",
    torque: "21.5 Nm @ 6.500 rpm",
    refrigeracion: "Aire + aceite (Oil-Cooled)",
    alimentacion: "Inyección electrónica FI",
    transmision: "5 velocidades",
    frenos: "ABS de doble canal + discos delantero y trasero",
    suspDel: "Horquilla telescópica 37 mm",
    suspTras: "Mono-shock Nitrox ajustable",
    peso: "162 kg aprox.",
    tanque: "14 litros",
    altura: "800 mm",
    velMax: "130–135 km/h aprox."
  },
  {
    id: 9,
    nombre: "Gixxer 250",
    img: "assets/gixxer250categorias3naked250.png",
    cilindraje: "249 cc, monocilíndrico, 4 tiempos, SOHC",
    potencia: "26.1 HP @ 9.300 rpm",
    torque: "22.2 Nm @ 7.300 rpm",
    refrigeracion: "Sistema SOCS (Oil Cooling System)",
    alimentacion: "Inyección electrónica FI",
    transmision: "6 velocidades",
    frenos: "ABS de doble canal + discos delantero y trasero",
    suspDel: "Horquilla telescópica",
    suspTras: "Mono-shock",
    peso: "156 kg",
    tanque: "12 litros",
    altura: "800 mm",
    velMax: "135–145 km/h aprox."
  },
  {
    id: 10,
    nombre: "CF Moto NK 250",
    img: "assets/cfnk250categorias3naked250.png",
    cilindraje: "249.2 cc, monocilíndrico, 4 tiempos, DOHC",
    potencia: "26 HP @ 9.500 rpm",
    torque: "22 Nm @ 7.500 rpm",
    refrigeracion: "Refrigeración líquida",
    alimentacion: "Inyección electrónica Bosch EFI",
    transmision: "6 velocidades",
    frenos: "ABS de doble canal + discos delantero y trasero",
    suspDel: "Horquilla telescópica",
    suspTras: "Mono-shock central",
    peso: "151 kg",
    tanque: "12.5 litros",
    altura: "795 mm",
    velMax: "135–140 km/h aprox."
  },
  {
    id: 11,
    nombre: "Yamaha FZ 250",
    img: "assets/yamahafz250categorias3naked250.png",
    cilindraje: "249 cc, monocilíndrico, 4 tiempos, SOHC",
    potencia: "20.8 HP @ 8.000 rpm",
    torque: "20.1 Nm @ 6.000 rpm",
    refrigeracion: "Aire + aceite (Oil-Cooled)",
    alimentacion: "Inyección electrónica FI",
    transmision: "5 velocidades",
    frenos: "ABS de doble canal + discos delantero y trasero",
    suspDel: "Horquilla telescópica",
    suspTras: "Mono-shock",
    peso: "148 kg",
    tanque: "14 litros",
    altura: "795 mm",
    velMax: "125–130 km/h aprox."
  },
  {
    id: 13,
    nombre: "KTM Duke 390",
    img: "assets/ktmduke390categorias3naked400.png",
    cilindraje: "373.2 cc, monocilíndrico, 4 tiempos, DOHC",
    potencia: "43 HP @ 9.000 rpm",
    torque: "37 Nm @ 7.000 rpm",
    refrigeracion: "Refrigeración líquida",
    alimentacion: "Inyección electrónica",
    transmision: "6 velocidades",
    frenos: "ABS de doble canal + discos delantero y trasero",
    suspDel: "Horquilla invertida WP APEX 43 mm",
    suspTras: "Mono-shock WP APEX",
    peso: "173 kg aprox.",
    tanque: "13.4 litros",
    altura: "830 mm",
    velMax: "160–170 km/h aprox."
  },
  {
    id: 14,
    nombre: "Kawasaki Z400",
    img: "assets/kawasakiz400categorias3naked400.png",
    cilindraje: "399 cc, bicilíndrica, 4 tiempos, DOHC",
    potencia: "45 HP @ 10.000 rpm",
    torque: "38 Nm @ 8.000 rpm",
    refrigeracion: "Líquida",
    alimentacion: "Inyección electrónica",
    transmision: "6 velocidades",
    frenos: "ABS de doble canal + discos delantero y trasero",
    suspDel: "Horquilla telescópica 41 mm",
    suspTras: "Mono-shock ajustable",
    peso: "167 kg",
    tanque: "14 litros",
    altura: "785 mm",
    velMax: "170–175 km/h aprox."
  },
  {
    id: 15,
    nombre: "Pulsar NS 400 Z",
    img: "assets/NS400Zcategorias3naked400.png",
    cilindraje: "373 cc, monocilíndrico, 4v, DOHC",
    potencia: "40 HP @ 8.800 rpm",
    torque: "35 Nm @ 6.500 rpm",
    refrigeracion: "Líquida",
    alimentacion: "Inyección electrónica EFI",
    transmision: "6 velocidades con Slipper Clutch",
    frenos: "ABS de doble canal + modos de manejo",
    suspDel: "Horquilla invertida USD",
    suspTras: "Mono-shock ajustable",
    peso: "174 kg",
    tanque: "12 litros",
    altura: "807 mm",
    velMax: "155–160 km/h aprox."
  },
  {
    id: 16,
    nombre: "Apache RTR 310",
    img: "assets/Apachertr310categorias3naked400.png",
    cilindraje: "312.2 cc, monocilíndrico, 4 tiempos, DOHC",
    potencia: "35.6 HP @ 9.700 rpm",
    torque: "28.7 Nm @ 6.650 rpm",
    refrigeracion: "Líquida",
    alimentacion: "Inyección electrónica",
    transmision: "6 velocidades con Slipper Clutch",
    frenos: "ABS con 5 modos de manejo",
    suspDel: "Horquilla invertida USD",
    suspTras: "Mono-shock ajustable",
    peso: "169 kg",
    tanque: "11 litros",
    altura: "800 mm",
    velMax: "150–160 km/h aprox."
  },
  {
    id: 18,
    nombre: "Husqvarna Vitpilen 401",
    img: "assets/husqvarna400categorias3naked400.png",
    cilindraje: "398.6 cc, monocilíndrico, DOHC",
    potencia: "44 HP @ 9.000 rpm",
    torque: "39 Nm @ 7.000 rpm",
    refrigeracion: "Líquida",
    alimentacion: "Inyección electrónica",
    transmision: "6 velocidades con embrague anti-rebote",
    frenos: "ABS Bosch + discos ByBre",
    suspDel: "WP APEX USD",
    suspTras: "WP APEX mono-shock",
    peso: "171 kg",
    tanque: "13 litros",
    altura: "820 mm",
    velMax: "160–165 km/h aprox."
  },
  {
    id: 19,
    nombre: "Aprilia Silver 750",
    img: "assets/Aprilia750categorias3naked750.png",
    cilindraje: "750 cc, bicilíndrico en V, DOHC",
    potencia: "92 HP @ 9.000 rpm",
    torque: "77 Nm @ 6.500 rpm",
    refrigeracion: "Líquida",
    alimentacion: "Inyección electrónica",
    transmision: "6 velocidades",
    frenos: "ABS Brembo de doble canal",
    suspDel: "Horquilla invertida Kayaba USD 41 mm",
    suspTras: "Mono-shock Kayaba ajustable",
    peso: "214 kg",
    tanque: "15 litros",
    altura: "830 mm",
    velMax: "210–220 km/h aprox."
  }
];
  motoSeleccionada1: any = null;
  motoSeleccionada2: any = null;

  seleccionarMoto1(event: Event) {
    const select = event.target as HTMLSelectElement;
    const id = Number(select.value);
    this.motoSeleccionada1 = this.motos.find(m => m.id === id) || null;
  }

  seleccionarMoto2(event: Event) {
    const select = event.target as HTMLSelectElement;
    const id = Number(select.value);
    this.motoSeleccionada2 = this.motos.find(m => m.id === id) || null;
  }

}
